org.gradle.jvmargs=-Xmx2048m
android.useAndroidX=true
android.nonTransitiveRClass=true

# Termux-এ aapt2 এর x86 বাইনারি কাজ করে না বলে এই লাইনটা দরকার হয়।
# README.md এর ধাপ অনুযায়ী এই পাথ ঠিক করে নিন (নিজের aapt2 এর আসল পাথ বসান)।
# android.aapt2FromMavenOverride=/data/data/com.termux/files/usr/bin/aapt2
